/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 house_and_solar_panels.glb 
Author: HeliosOptimum (https://sketchfab.com/HeliosOptimum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-and-solar-panels-09536a733d1445358cc69ea82df5c927
Title: House and Solar Panels
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/house_and_solar_panels.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
        <mesh geometry={nodes.Material2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Roofing_Metal_Standing_Seam_Red} />
        <lineSegments geometry={nodes.Material5.geometry} material={materials.edge_color254254254255} />
        <lineSegments geometry={nodes.Material6.geometry} material={materials.edge_color1458939255} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Wood_Floor_Parquet} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Wood_Bamboo} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Translucent_Glass_Gray} />
        <lineSegments geometry={nodes.Material6_1.geometry} material={materials.edge_color1207037255} />
        <lineSegments geometry={nodes.Material7.geometry} material={materials.edge_color1528642255} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Wood_Veneer_01} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Roofing_Tile_Spanish} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Blinds_Vertical_Stripe_Gray} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Wood_Cherry_Original} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.Black} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.Color_M07} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.Color_M08} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.Material2} />
        <lineSegments geometry={nodes.Material3_2.geometry} material={materials.edge_color585858255} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.Color_007} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.mono_x_lg_solar_panel} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.Wheel_Charcoal} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.Gainsboro} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.Car_Body_Silver} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.Gray_Glass} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.Brake_Light_Red} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.Light_White_Smoke} />
        <lineSegments geometry={nodes.Material2_20.geometry} material={materials.edge_color000255} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/house_and_solar_panels.glb')
